### ISSUE TITLE
Issue running the .py

### ISSUE THREAD

**Issue by idkthing** [moom825/Discord-RAT#13]
So when I run the .py file it just closes after a few seconds, how do I fix this?

**Comment by idkthing** [comment]
Got this erro
![Screenshot 2021-10-29 165419](https://user-images.githubusercontent.com/84043486/139505779-034ffc91-a9ae-4356-beba-19110c2626e7.png)
r

**Comment by idkthing** [comment]
How do I fix that?

**Comment by moom825** [comment]
sorry for the late response.

are you sure you put the bot token in the correct place?

**Comment by idkthing** [comment]
Pretty sure

**Comment by idkthing** [comment]
I can check later

**Comment by idkthing** [comment]
What python version should I use?

**Comment by moom825** [comment]
3.6- 3.9

**Comment by idkthing** [comment]
I have 3.7 and 3.9

**Comment by idkthing** [comment]
C:\Users\schutz_899830\Music\DiscordRAT\DiscordRAT>python DiscordRAT.py
Traceback (most recent call last):
  File "DiscordRAT.py", line 1469, in <module>
    client.run(token)
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 563, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\schutz_899830\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 974, in get_gateway
    return value.format(data['url'], encoding, v)
TypeError: string indices must be integers
That is error, how do I fix?

**Comment by moom825** [comment]
you put the bot token in right?

**Comment by idkthing** [comment]
Yes

**Comment by idkthing** [comment]
![Screenshot 2021-11-03 183830](https://user-images.githubusercontent.com/84043486/140233553-30f9ce2d-26c3-439c-b8df-3cb8e33abb38.png)

**Comment by idkthing** [comment]
This is a issue for most .py files too, if not all

**Comment by moom825** [comment]
message me on discord. moom825#0001
