### ISSUE TITLE
!displaydir

### ISSUE THREAD

**Issue by dreamywashere** [moom825/Discord-RAT#25]
noring exception in on_message
Traceback (most recent call last):
  File "C:\Users\drm\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\drm\Desktop\DiscordRAT-master\DiscordRAT.py", line 695, in on_message
    numb = len(result)
TypeError: object of type 'CompletedProcess' has no len()

**Comment by moom825** [comment]
should be fixed, message me if problem persists
