### ISSUE TITLE
AttributeError: 'DMChannel' object has no attribute 'name'

### ISSUE THREAD

**Issue by rohanraj-aipro** [moom825/Discord-RAT#44]
[2022-11-11 22:38:03] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\kanch\AppData\Local\Temp\Rar$DIa3860.7251\DiscordRAT.py", line 183, in on_message
    if message.channel.name != channel_name:
AttributeError: 'DMChannel' object has no attribute 'name'

**Comment by moom825** [comment]
are you dming the bot? why?

**Comment by moom825** [comment]
also please use 2.0

**Comment by rohanraj-aipro** [comment]
where to send command ? not dming ?

**Comment by moom825** [comment]
it should create a channel in the server u added it to

**Comment by rohanraj-aipro** [comment]
did you mean session-1 ?

**Comment by rohanraj-aipro** [comment]
![discord](https://user-images.githubusercontent.com/85404080/202886233-89a2d076-a5a8-436c-9a52-988c6cff1be9.png)

**Comment by rohanraj-aipro** [comment]
i used volumemax command. not working

**Comment by rohanraj-aipro** [comment]
infact, any command is not working

**Comment by ghost** [comment]
you just got rated!

**Comment by rohanraj-aipro** [comment]
Huh?

Rated or Ratted?
