### ISSUE TITLE
    raise RemoteDisconnected("Remote end closed connection without"

### ISSUE THREAD

**Issue by rohanraj-aipro** [moom825/Discord-RAT#47]
[2022-11-29 21:15:00] [INFO    ] discord.client: logging in using static token
[2022-11-29 21:15:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0079caf86746f284617076e33134f610).
[2022-11-29 21:15:06] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\kanch\OneDrive\Desktop\Discord-RAT-main\DiscordRAT.py", line 126, in on_ready
    with urllib.request.urlopen("https://geolocation-db.com/json") as url:
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\kanch\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by rohanraj-aipro** [comment]
I solved it. Just make sure that the link "https://geolocation-db.com/json" is working by opening it manually. 

if it displays your ip address, it is working. if it displays someting lese, then you should probably use a vpn/proxychains or something to make that work
